spring:
  application:
    name: Curiosity
  resources:
    add-mappings: false
server:
  port: 8080
  context-path: /rest
mars:
  bounds:
    min-x: 0
    max-x: 5
    min-y: 0
    max-y: 5
  initial-position:
    x: 0
    y: 0
    direction: N